DROP TABLE FIXBUSINESSREJECT;
CREATE TABLE FIXBUSINESSREJECT (
	DBBUSINESSREJECTID	INTEGER	NOT NULL,
	REFSEQNUM	INTEGER	,
	TEXT	VARCHAR(18)	,
	REFMSGTYPE	CHAR(2)	,
	BUSINESSREJECTREASON	SMALLINT	,
	CREATEDBY VARCHAR(32),
	CREATIONDATE TIMESTAMP,
	LASTMODIFIEDBY VARCHAR(32),
	LASTMODIFIEDDATE TIMESTAMP
)
