DROP TABLE FIXCODECATEGORY;
CREATE TABLE FIXCODECATEGORY (
	CATEGORYID	INTEGER	NOT NULL,
	DESCRIPTION	VARCHAR(100),
	CREATEDBY VARCHAR(32),
	CREATIONDATE TIMESTAMP,
	LASTMODIFIEDBY VARCHAR(32),
	LASTMODIFIEDDATE TIMESTAMP
)
