package com.exsys.mktdata.cfg;

/**
 * Created on Feb 10, 2005
 */
public class ConfigurationException extends Exception {
	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = -6561478455612446773L;

	public ConfigurationException(String msg) {
        super(msg);
    }

    public ConfigurationException(String msg, Throwable t) {
        super(msg,t);
    }

}
