INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(21,'HandlInst');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(40,'Order Type');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'1','Market');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'2','Limit');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'3','Stop');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'4','Stop limit');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'5','Market on close');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'6','With or without');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'7','Limit or better');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'8','Limit with or without');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'9','On basis');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'A','On close');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'B','Limit on close');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'C','Forex - Market');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'D','Previously quoted');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'E','Previously indicated');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'F','Forex - Limit');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'G','Forex - Swap');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'H','Forex - Previously Quoted');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'I','Funari (Limit Day Order with unexecuted portion handled as Market On Close.   e.g. Japan)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'K','Market-Limit');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(40,	'P','Pegged (requires ExecInst = L, R, M, P or O)');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(54,'Side of order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'1','Buy');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'2','Sell');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'3','Buy minus');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'4','Sell plus');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'5','Sell short');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'6','Sell short exempt');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'7','Undisclosed (valid for IOI and List Order messages only)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'8','Cross (orders where counterparty is an exchange, valid for all messages except IOIs)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(54,	'9','Cross short');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(59,'TimeInForce');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(59,	'0','Day');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(59,	'1','Good Till Cancel  (GTC)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(59,	'2','At the Opening  (OPG)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(59,	'3','Immediate or Cancel  (OC)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(59,	'4','Fill or Kill  (FOK)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(59,	'5','Good Till Crossing  (GTX)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(59,	'6','Good Till Date'); 

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(63,'SettlementType');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'0','Regular');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'1','Cash');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'2','Next Day');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'3','T+2');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'4','T+3');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'5','T+4');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'6','Future');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'7','When Issued');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'8','Sellers Option');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(63,	'9','T+ 5');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(77,'OpenClose');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(77,	'O', 'O=Open');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(77,	'C', 'C=Close');
	
INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(81,'ProcessCode');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(81,	'0','regular');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(81,	'1','soft dollar');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(81,	'2','step-in');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(81,	'3','step-out');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(81,	'4','soft-dollar step-in');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(81,	'5','soft-dollar step-out');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(81,	'6','plan sponsor'); 


INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(167,'SecurityType');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'BA','Bankers Acceptance');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'CB','Convertible Bond (Note not part of ISITC spec)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'CD','Certificate Of Deposit');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'CMO','Collateralize Mortgage Obligation');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'CORP','Corporate Bond');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'CP','Commercial Paper');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'CPP','Corporate Private Placement');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'CS','Common Stock');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'FHA','Federal Housing Authority');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'FHL','Federal Home Loan');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'FN','Federal National Mortgage Association');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'FOR','Foreign Exchange Contract');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'FUT','Future');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'GN','Government National Mortgage Association');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'GOVT','Treasuries + Agency Debenture');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'IET','Mortgage IOETTE');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'MF','Mutual Fund');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'MIO','Mortgage Interest Only');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'MPO','Mortgage Principal Only');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'MPP','Mortgage Private Placement');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'MPT','Miscellaneous Pass-Thru');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'MUNI','Municipal Bond');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'NONE','No ISITC Security Type');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'OPT','Option');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'PS','Preferred Stock');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'RP','Repurchase Agreement');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'RVRP','Reverse Repurchase Agreement');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'SL','Student Loan Marketing Association');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'TD','Time Deposit');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'USTB','US Treasury Bill');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'WAR','Warrant');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(167,	'ZOO','Cats, Tigers & Lions (a real code: US Treasury Receipts) ');


INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(201,'PutOrCall');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(201,	'0','Put');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(201,	'1','Call');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(204,'CustomerOrFirm');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(204,	'0','Customer');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(204,	'1','Firm');


INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(388,'DiscretionInst');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(388,	'0','Related to displayed price');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(388,	'1','Related to market price');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(388,	'2','Related to primary price');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(388,	'3','Related to local primary price');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(388,	'4','Related to midpoint price');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(388,	'5','Related to last trade price');


INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(380,'BusinessRejectReason');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(380,	'0','Other');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(380,	'1','Unkown ID');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(380,	'2','Unknown Security');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(380,	'3','Unsupported Message Type');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(380,	'4','Application not available');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(380,	'5','Conditionally Required Field Missing');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(102,'Cxl Reject Reason');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(102,	'0','Too late to cancel');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(102,	'1','Unknown order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(102,	'2','Broker Option');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(102,	'3','Order already in Pending Cancel or Pending Replace status');


INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(434,'CxlRejResponseTo');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(434,	'1','Order Cancel Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(434,	'2','Order Cancel/Replace Request');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(35,'MsgType');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'0','Heartbeat');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'1','Test Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'2','Resend Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'3','Reject');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'4','Sequence Reset');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'5','Logout');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'6','Indication of Interest');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'7','Advertisement');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'8','Execution Report');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'9','Order Cancel Reject');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'A','Logon');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'B','News');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'C','Email');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'D','Order  Single');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'E','Order  List');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'F','Order Cancel Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'G','Order Cancel/Replace Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'H','Order Status Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'J','Allocation');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'K','List Cancel Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'L','List Execute');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'M','List Status Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'N','List Status');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'P','Allocation ACK');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'Q','Don’t Know Trade (DK)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'R','Quote Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'S','Quote');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'T','Settlement Instructions');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'V','Market Data Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'W','Market Data-Snapshot/Full Refresh');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'X','Market Data-Incremental Refresh');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'Y','Market Data Request Reject');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'Z','Quote Cancel');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'a',' Quote Status Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'b',' Quote Acknowledgement');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'c','Security Definition Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'd','Security Definition');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'e','Security Status Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'f','Security Status');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'g','Trading Session Status Request');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'h','Trading Session Status');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'i','Mass Quote');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'j','Business Message Reject');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'k','Bid Request'); 
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'l','Bid Response (lowercase L)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(35,	'm','List Strike Price');


INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(20,'ExecTransType');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(20,	'0','New ');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(20,	'1','Cancel');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(20,	'2','Correct');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(20,	'3','Status');
	
INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(39,'OrdStatus');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'0','New');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'1','Partially filled');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'2','Filled');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'3','Done for day');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'4','Canceled');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'5','Replaced');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'6','Pending Cancel (e.g. result of Order Cancel Request) 7 = Stopped');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'8','Rejected');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'9','Suspended');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'A','Pending New');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'B','Calculated');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'C','Expired');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'D','Accepted for bidding');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(39,	'E','Pending Replace (e.g. result of Order Cancel/Replace Request)');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(103,'OrdRejReason');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'0','Broker option');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'1','Unknown symbol');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'2','Exchange closed');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'3','Order exceeds limit');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'4','Too late to enter');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'5','Unknown Order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'6','Duplicate Order (e.g. dupe ClOrdID)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'7','Duplicate of a verbally communicated order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(103,	'8','Stale Order');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(150,'ExecType');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'0','New');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'1','Partial fill');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'2','Fill');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'3','Done for day');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'4','Canceled');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'5','Replace');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'6','Pending Cancel  (e.g. result of Order Cancel Request)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'7','Stopped');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'8','Rejected');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'9','Suspended');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'A','Pending New');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'B','Calculated');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'C','Expired');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'D','Restated (ExecutionRpt sent unsolicited by sellside, with ExecRestatementReason set)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(150,	'E','Pending Replace (e.g. result of Order Cancel/Replace Request)');

INSERT INTO FIXCODECATEGORY(CATEGORYID,DESCRIPTION)VALUES(378,'ExecRestatementReason');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(378,	'0','GT Corporate action');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(378,	'1','GT renewal / restatement (no corporate action)');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(378,	'2','Verbal change');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(378,	'3','Repricing of order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(378,	'4','Broker option');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(378,	'5','Partial decline of OrderQty (e.g. exchange-initiated partial cancel)');