INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');

INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
INSERT INTO FIXCODEVALUE(CATEGORYID,FIXCODE,FIXVALUE)VALUES(21,'1','Automated execution order');
