DROP TABLE FIXCODEVALUE;
CREATE TABLE FIXCODEVALUE (
	CATEGORYID	INTEGER	NOT NULL,
	FIXCODE		VARCHAR(10),
	FIXVALUE	VARCHAR(100),
	CREATEDBY VARCHAR(32),
	CREATIONDATE TIMESTAMP,
	LASTMODIFIEDBY VARCHAR(32),
	LASTMODIFIEDDATE TIMESTAMP
)